### ISSUE TITLE
Selected item is preloaded for edit when trying to add task

### ISSUE THREAD

**Issue by jflinchbaugh** [mpcjanssen/simpletask-android#654] opened 2016-10-14 13:35 UTC
Simpletask 8.3.0

If there's a selected item in a list, trying to add a new item from a widget '+' button loads that selected item for editing instead of presenting a fresh entry.

Reproduction:
* ensure you have a simpletask list widget on homescreen
* open a list
* select an item
* go back to home screen
* click '+' on a home screen widget
* see it preloaded the selected item
* delete text and type something else
* see that it EDITED the previously selected one, not added a new one! (ouch)

Expected behavior:
* '+' should always clear the current selection and present me a fresh new pane to type my new task.  

I noticed that the '+' action disappears in the application when anything is selected to keep this from happening. I have to unselect or 'back' to get the '+' action to reappear.  If it always cleared the selection, then the action wouldn't need to be hidden there either.

**Comment by smichel17** [comment] 2016-10-14 13:42
Duplicate of #547. Related: #638.

**Comment by mpcjanssen** [comment] 2016-10-17 13:34
Closed as duplicate of #547

**Closed by mpcjanssen** 2016-10-17 13:34 UTC
