### ISSUE TITLE
The 'custom font size' setting does not take effect until after activity recreation

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#756] opened 2017-05-30 18:11 UTC
Steps:
- Open Settings > Appearance
- Change the 'Custom font size' setting
- Press the back arrow twice to return to the main activity

Expected: Font size reflects the changed setting
Actual: Font size does not change until simpletask is closed (using the back key, or home + remove from recent apps) and re-opened.

---
Related: When `Custom font size` is disabled, we should do one of:
- Hide the slider entirely instead of just disabling it
  - If we do this, we should do the same with the settings that depend on `Show datebar`
- Change the value of the (disabled) slider to the default font size (14sp).
  - Alternatively, don't change the slider value, but *do* change the text.
  - When it is re-enabled, it should jump back to the saved value.

*Slight* preference for the second option.

---
I can make a PR for this.

**Comment by mpcjanssen** [comment] 2017-06-15 09:10
@smichel17 in 9.0.6 the custom font size is broken. I suspect this is caused by the Preference update, could you have a look?

**Comment by agrudzinsky** [comment] 2017-06-15 16:44
Same here. Got a 9.0.6 update notification this morning and noticed that the font is too small.  Tried to adjust - no effect. Restarting the app did not help.

**Comment by mpcjanssen** [comment] 2017-06-15 18:49
@agrudzinsky that particular issue will be fixed in the next release (today or tomorrow)

**Comment by smichel17** [comment] 2017-06-15 19:40
@agrudzinsky Issue was a typo where the custom font size setting does the exact opposite of what it should. Workaround until tomorrow is to uncheck custom font size.

**Closed** 2017-06-16 08:25 UTC
