### ISSUE TITLE
"Loading of todo file failed" Dropbox version 10.9.3

### ISSUE THREAD

**Issue by jason-mehmel** [mpcjanssen/simpletask-android#1163] opened 2022-04-20 18:19 UTC
New behaviour as of last night, getting this error response.

I've since tried updating the phone, closing and opening the app, and reinstalling it.

From the reinstalled state, logging in via Dropbox, I am getting the same response!

Not sure if something changed with Dropbox overnight?

**Comment by mpcjanssen** [comment] 2022-04-20 19:17
Duplicate of #1157

**Comment by jason-mehmel** [comment] 2022-04-20 20:27
I have checked and the PKCE version works! Including the widget!

Thank you for all your work!

**Closed** 2022-04-21 06:09 UTC
