### ISSUE TITLE
tag list has no check boxes when task selected

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#698] opened 2016-12-15 14:34 UTC
When I select a task and then tap the tags button, there are no check boxes for the tags. The selected tags are at the top, sorted before all other available tags, but there are neither check boxes visible, nor check marks for the already present tags -- see attached image with pixelized tags.

Selecting and deselecting seems to work as desired, but this way no visual check is possible.

In contrast, when tapping the tags button while in editing mode, check boxes and check marks are visible.

![selectedtask_taglist](https://cloud.githubusercontent.com/assets/8195964/21227810/b6171d98-c2db-11e6-98c8-30d0799bd933.png)

**Comment by smichel17** [comment] 2016-12-15 15:34
Duplicate of #690

**Comment by aurisnoctis** [comment] 2016-12-15 15:39
Accepted as duplicate if lists (`@`, issue #690 ) and tags (`+`, this issue) are handled the same way.

**Closed** 2016-12-15 16:55 UTC

**Comment by mpcjanssen** [comment] 2017-01-07 18:24
@aurisnoctis yep same issue for tags and lists.
