### ISSUE TITLE
Error showing task with multiple context or project

### ISSUE THREAD

**Issue by mimmori** [mpcjanssen/simpletask-android#984] opened 2019-06-22 14:45 UTC
I want to report a bug in the show of the task contained multiple context or project (C/P).
When I chose to sort my tasks by C/P all the task that contains more than one tag is showed only in the first C/P found.

Example:

Todo.txt contents:
Task 1 @context1 @context2

Show filtering by context:

context1:
Task 1

context2:
(Void)

I expect to see the task on both context lists.
The same happen with the project.

**Comment by mpcjanssen** [comment] 2019-06-23 10:36
Duplicate of #153

**Closed by mpcjanssen** 2019-06-23 10:36 UTC
