### ISSUE TITLE
Multiple contexts are not supported

### ISSUE THREAD

**Issue by joereynolds** [mpcjanssen/simpletask-android#951] opened 2018-11-20 12:18 UTC
I have a task with the following 

```
Hardcase for prs @shop @home
```

On Simpletask (dropbox) it is only showing in the `home` context, I would expect it to be visible in both `home` and `shop`.

When I change this task to 

```
Hardcase for prs @shop
```

It is then visible in the `shop` category.

Thanks :)

**Comment by mpcjanssen** [comment] 2018-11-20 14:07
Duplicate of #153

**Closed** 2018-11-20 14:08 UTC
Labels: duplicate

**Comment by mpcjanssen** [comment] 2018-11-20 14:10
Assuming you mean it is only visible under the @home header. Not that it's not visible if you filter on @shop. Note that only grouping by context is not a good way to see which tasks are in which contexts, filtering by context is the proper way.
