### ISSUE TITLE
Sort order and "Other" options persist after clearing filter

### ISSUE THREAD

**Issue by Vijayanth-Reddy-K** [mpcjanssen/simpletask-android#706] opened 2017-01-23 12:11 UTC
Steps to reproduce:

1. Clear any filter that has been applied.
2. Change sort order and `Other` options.
3. Apply saved filter which has a different sort order or create a new filter with a different sort order and `Other` options (such as toggling visibility of completed tasks).
4. Clear the filter.
5. Settings such as list and tag filter and grouping via Lua scripts get cleared. But the sort order and other options that were set do not get cleared.

**Drawback**: If you have multiple widgets with different sort orders, any time you open one of them, and then clear, the options change.

**Solution**: Remember the options and order when there is no filter or script running, and revert to those when the filter/script is cleared.

**Temporary Workaround**: Clear all filters and apply the "default" sort order and options you wish. And save as a filter (probably called Default). Whenever you wish to revert to those default options, apply saved filter and clear the filter.

But it would be nice to have a permanent solution if it is not too hard.

**Comment by smichel17** [comment] 2017-01-23 14:10
I have the same filter (called `all`).

@mpcjanssen and I have talked about some changes to the way saved filters work (queries), which there might be an issue about or you might have to go scroll back far in the gitter.im history. It's just that they require some significant refactoring (which the code needs anyway), and I'm not really comfortable doing that on my own (though I will do cleanup once @mpcjanssen does the main split). He's been busy with real life and so I've been focusing my time elsewhere for the moment. When that changes,  this will likely be one of the first things we'll get to.

**Comment by Vijayanth-Reddy-K** [comment] 2017-01-23 15:36
Sure. It's just that I did not know filters can be saved until recently and when I was trying to play around with the options, I realized that the sort order and options "stuck" after the filter was cleared and decided to bring it to your attention. ☺️

**Comment by mpcjanssen** [comment] 2017-01-31 13:45
Closing this. It works as intended and there are other issues discussion behavior and UI updates.

**Closed by mpcjanssen** 2017-01-31 13:45 UTC
