### ISSUE TITLE
Allow custom font for task list.

### ISSUE THREAD

**Issue by memeplex** [mpcjanssen/simpletask-android#482] opened 2016-07-13 23:49 UTC
I customized the font from the settings window but nothing happened. I tried with many fonts to no avail. Besides there seems to be a problem with 0/1-based indexing, because after returning to the font picker the one selected is the one before the originally selected.

**Comment by smichel17** [comment] 2016-07-14 12:40
Tested this; the setting also has no effect for me.

**Comment by mpcjanssen** [comment] 2016-07-14 14:14
Correct on both counts. This functionality is actually not implemented yet (only the setting is there)

**Comment by mpcjanssen** [comment] 2016-07-16 12:56
Retagged enhancement as a reminder to implement it again.

**Comment by mpcjanssen** [comment] 2016-07-16 12:56
Then duplicate of #449

**Closed by mpcjanssen** 2016-07-16 12:56 UTC
Labels: enhancement
