### ISSUE TITLE
WebDAV sync, with the new version 10.9.2 update, does not work.

### ISSUE THREAD

**Issue by uGeek** [mpcjanssen/simpletask-android#1128] opened 2021-09-06 13:37 UTC
When upgrading to version 10.9.2 update, it does not work. I have returned to the previous version and without problems.

The error happens to me on two mobile devices

**Comment by mpcjanssen** [comment] 2021-09-06 14:28
Duplicate of #1126

**Closed** 2021-09-06 14:28 UTC
