### ISSUE TITLE
After sharing AddTask shows up as another app

### ISSUE THREAD

**Issue by memeplex** [mpcjanssen/simpletask-android#487] opened 2016-07-14 15:37 UTC
This is annoying and error prone since app lists and switchers tend to use the icon as the main identifier and you get two st icons around and frequently open addtask by mistake. I don't know much about android, really, but many apps allow to share without producing this artifact.

**Comment by smichel17** [comment] 2016-07-14 16:53
I cannot reproduce this. Can you provide more precise steps?

**Comment by memeplex** [comment] 2016-07-14 16:57
Sure:

1. Open st as usual.
2. Return to this page and share it to st.
3. Open your app manager/switcher.
4. You will see two apps: Add Task and Simpletask.

There is nothing wrong per se with this but on the usability side I would say it's lacking.

**Comment by memeplex** [comment] 2016-07-14 16:58
Btw I'm testing this with kitkat task manager and with the wonderful eas app.

**Comment by smichel17** [comment] 2016-07-14 17:12
Got'cha. This was intended, as a fix for this bug:

1. Open st as usual.
2. Edit a task, but don't save
3. Go to the home screen without saving your shared task
4. Re-open simpletask through a widget or saved filter
5. Edits are lost

With the change, step 5 becomes "Use the app switcher to return to the addtask screen and finish editing/save your task"

---

I'm assuming this is a problem for you because kitkat task manager only shows icons (or only shows them prominently) so it's hard or impossible to distinguish between simpletask and the Add Task screen.

I see three solutions:

1. Change the icon for `Add Task`
  - Candidate: replace the check mark with a plus
2. In my step 4 above, save the edits instead of discarding them.
3. In my step 4 above, have simpletask show the tasks you were editing first, then when you save or discard them, show whatever else you were coming to simpletask for.
  - This probably makes the most sense, but runs the risk of piling up a huge number of Add Task screens before you can get to simpletask, if you repeatedly share things to simpletask without saving them.
    - This could be mitigated if sharing something to simpletask while on the Add Task screen appends the shared items to the existing Add Task screen, instead of opening a new Add Task screen behind it. That might add a lot of complexity, though; I'll have to check with @mpcjanssen

**Comment by memeplex** [comment] 2016-07-14 17:20
I think solution 3 is the most sensible, but I would like to simplify the proposal. Let's differentiate between action A (add task) and action B (filter, add another task, etc.). You fear a queue of A, B, C, ... actions, I understand that concern. But I would say you shouldn't be doing that and indeed you probably won't be doing that so often even by chance. So why don't st just forget about B when there is still an A in course? This says to the user: yeah, you want B but you still have to do A, so finish A, then *you* recall B.

**Comment by smichel17** [comment] 2016-07-15 02:38
I will admit my 'fear' is a bit of a corner case. If I quit the app without saving again after action B, and then take action C that opens the app, I only need to save action B if it was a share action. So the only way we could end up with a queue is if someone repeatedly shared something to simpletask, closed the app without saving, then shared again, etc.

Still, you need logic in place to handle corner cases. Perhaps in this one, sharing to simpletask while the editor is open adds the tasks you shared without giving you a chance to edit them, then brings you to the editor with the tasks you were editing when you left.

Or we could do your solution (4), where it doesn't matter what brought you to simpletask; if you were in the middle of editing a task when you left, you're returned to editing and whatever brought you to simpletask is forgotten about.

**Comment by mpcjanssen** [comment] 2016-08-16 12:32
I will look into scenario 3 where the AddTask activity will retain pending edits.

**Comment by smichel17** [comment] 2016-08-18 12:48
It occurs to me in retrospect that since you can add/edit multiple tasks at once, if I share something to Simpletask while in the middle of editing/adding a task, the new thing should be appended to the existing addTask screen.

**Comment by smichel17** [comment] 2016-08-20 12:53
@mpcjanssen I think I agree with @memeplex here. Simpletask should only appear once in the history. If I'm editing something, go to the home screen, then open simpletask from a widget, I should return to the edit screen and the widget's filter should be selected in the background, after I finish editing.

**Comment by smichel17** [comment] 2016-08-23 20:39
Found the old issue that caused this. It's #129.

**Comment by mpcjanssen** [comment] 2016-10-01 09:59
Seems the activity fix is the wrong way to fix #129. I will undo the change that caused this and think of a better way to fix #129.

**Comment by mpcjanssen** [comment] 2016-10-01 10:21
Seems this is already reverted in latest master.

**Comment by mpcjanssen** [comment] 2016-10-01 10:30
Ok I was wrong. It's not.

**Closed** 2016-10-01 10:39 UTC
Labels: enhancement
