### ISSUE TITLE
onFilter does not filter out future due dates in widget

### ISSUE THREAD

**Issue by smyslim** [mpcjanssen/simpletask-android#502] opened 2016-07-18 17:55 UTC
When the following script is used in app filter it works fine, showing what i need: tasks due today and tasks overdue.
But same script used in widget filter gives a different result, it shows all tasks which have due dates: due today, overdue and future due dates.
Am I doing something wrong or is it a bug?

`function onFilter(t,f,e)
  if f.due~=nil then
      return os.time() > f.due;
  end
  --- tasks with no due date are not overdue.
  return false;
end`

**Comment by smichel17** [comment] 2016-07-18 19:14
Which simpletask version are you using? There was a bug with widgets that was fixed in 8.05 or 8.06, I believe.

**Comment by smyslim** [comment] 2016-07-18 19:20
I am using Simpletask version 8.1.0, the last update available at PlayMarket. 
Android 6.0.1

**Comment by cruzccl** [comment] 2016-07-18 20:24
Same thing here about a week ago: widgets do not show the same tasks than they do when you open Simpletask tapping on them (inside the app the filter works, in the widget filter is not ok).

I have some complex filters and I am debugging which filter behave this weird way (besides due), I report here any conclusion :)

Simpletask v8.1.0 on Android 6.0.1 too.

**Comment by cruzccl** [comment] 2016-07-18 20:44
I think the problem is related to calling os.time() in widgets filter, does this make sense to you? :S

**Comment by smichel17** [comment] 2016-07-18 20:45
The bug that was happening before 8.05 was: all lua was running in a single context, so although onFilter was defined in each widget, it was getting overwritten by whichever other filter got loaded most recently. Each filter and widget now has its own context so this shouldn't happen any more. To test whether it is the same bug resurfacing, you can try changing the active filter in the app and then see if that has any effect on the tasks shown in the filter.

>I think the problem is related to calling os.time() in widgets filter

I'll do some testing too and see if I can confirm. Rather tired right now so I might not get around to it until tomorrow.

---

aside @smyslim: I believe you can shorten that filter to:
```
function onFilter(t,f,e)
  return f.due and os.time() > f.due;
end
```

**Comment by cruzccl** [comment] 2016-07-18 21:02
> To test whether it is the same bug resurfacing, you can try changing the active filter in the app and then see if that has any effect on the tasks shown in the filter.

I doesn't seem to have any effect.

Filters not having os.time() function are working fine to me both in widget and in app, I think the problem is somehow related to that.

Thank you.

**Comment by mpcjanssen** [comment] 2016-07-19 07:06
It's indeed an issue wit os.time being nil. Will look into it.

**Comment by mpcjanssen** [comment] 2016-07-19 07:10
Do you see any errots in the log?

**Comment by mpcjanssen** [comment] 2016-07-19 07:34
Seems not to be os.time () after all but the incorrect filter being run. Seems that the widget is using an older version of the filter.

**Comment by mpcjanssen** [comment] 2016-07-19 07:54
Update code is not run in interpreter before applying the filter on ActiveFilter.apply

**Comment by cruzccl** [comment] 2016-07-20 19:20
> Do you see any errors in the log?

I think every message is just informational and logs include lua scripts as expected. I am not an expert though...

> Update code is not run in interpreter before applying the filter on ActiveFilter.apply

Does this mean that this problem is hard to solve? 
I use the widget to show important tasks at a glance in my main screen and it is quite useless now :S

Tell me please if I can help to have this solved asap.

Thank you, regards.

**Comment by mpcjanssen** [comment] 2016-07-23 07:30
At the moment, I dont really know what is causing this, but I can reproduce it ao that helps.

**Comment by mpcjanssen** [comment] 2016-07-23 08:23
The problem is that in the scope of executing the widget code, global functions are not available for some reason.

**Comment by mpcjanssen** [comment] 2016-07-23 08:42
Seems the whole approach of loading the callback in a table isn't working.

**Comment by mpcjanssen** [comment] 2016-07-23 09:45
Most robust way to fix this is to  create a different interpreter for every filter.

**Closed** 2016-07-23 13:40 UTC
Labels: bug, planned

**Comment by smyslim** [comment] 2016-08-10 13:11
@smichel17 thank you for the shortcut code, will try it.

**Comment by smichel17** [comment] 2016-08-10 14:05
@smyslim no problem. Normally I prefer to write out the logic using if/then statements because -- while just returning the values is fun to program -- it's much less readable to someone who's not familiar with the particular language. In this case, though, it's still really clear what's going on :smile:
