### ISSUE TITLE
[multi select] Do not add tags or lists unless the user explicitly does so

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#384] opened 2016-03-11 04:44 UTC
Say my todo.txt looks like:
```
a @a
ab @a @b
```
I select both items, edit lists, and remove `@a`. Afterward, I'd expect my todo.txt file to look like:
```
a
ab @b
```
but instead I get this
```
a @b
ab @b
```
Commonly, this is implemented with a gui distinction for "some items are in this list" vs "all items are in this list". Call it 'half-checked'.

Say there's another item `c @c` in the file. When you select `a` and `ab` and edit lists, you have `@a` fully-checked, `@b` half-checked, and `@c` unchecked.

- If you click `@a`, both items are removed from list a.
- If you click `@c`, both items are added to list c.
- If you click `@b` once, `a` is added to list b and the label becomes fully-checked.
- If you click `@b` again, both items are removed from list b. 

---

Summary: if I multi-select but don't change a given tag/list, none of the selected items should have that list added or removed.

**Comment by mpcjanssen** [comment] 2016-03-11 08:58
This needs a tri-state checkbox. Duplicate of #149

**Closed by mpcjanssen** 2016-03-11 08:58 UTC
