### ISSUE TITLE
Filter keeps getting removed

### ISSUE THREAD

**Issue by nthorne** [mpcjanssen/simpletask-android#867] opened 2018-03-01 20:42 UTC
I have 13 filters defined, but one of them keeps getting removed all the time for some strange reason. This started happening after updating to 10.1.2.

The export looks like this:
```
  "Assigned to a day": {
    "TITLE": "Assigned to a day",
    "CONTEXTS": "1.monday\n2.tuesday\n3.wednesday\n4.thursday\n5.friday\n6.saturday\n7.sunday",
    "CONTEXTSnot": false,
    "PROJECTS": "",
    "PROJECTSnot": false,
    "PRIORITIES": "",
    "PRIORITIESnot": false,
    "SORTS": "+!by_context\n+!in_future\n+!completed\n+!by_prio\n+!by_due_date\n+!by_project\n+!alphabetical\n+!file_order\n+!by_creation_date\n+!by_threshold_date\n+!by_completion_date\n+!by_lua",
    "HIDECOMPLETED": true,
    "HIDEFUTURE": true,
    "HIDELISTS": false,
    "HIDETAGS": false,
    "HIDECREATEDATE": false,
    "HIDEHIDDEN": true,
    "CREATEISTHRESHOLD": false,
    "LUASCRIPT": "",
    "USE_SCRIPT": false,
    "LUASCRIPT_TEST_TASK": "",
    "query": ""
  },
```

**Comment by nthorne** [comment] 2018-03-01 21:07
.. the removal does not happen straight away after importing the filter, btw.

**Comment by smichel17** [comment] 2018-03-02 00:35
If you import the filter, close the app, swipe it away from the list of recent apps, and then re-open it, does this trigger the bug?

It is only for imported filters or for any newly saved filter?

**Comment by nthorne** [comment] 2018-03-02 04:39
1. No
2. Only this particular filter was dropped; both after the update, then after each import. Creating it from scratch seemed to make it stick..

**Comment by mpcjanssen** [comment] 2018-03-02 09:23
@smichel17 might the `"query": ""` be related?

**Comment by nthorne** [comment] 2018-03-02 11:14
Also, when this happens, the last filter in the list, which is my widget filter, gets duplicated.

**Comment by smichel17** [comment] 2018-03-02 13:46
@mpcjanssen Did a little testing but I'm not sure. No time now, will have some in ~24h

**Comment by smichel17** [comment] 2018-03-02 13:52
@mpcjanssen Query field should not be in the export at all and we should be giving queries a newly generated id on import.

I'm not sure if I ever implemented that, so I would not be surprised if it were broken.

**Comment by nthorne** [comment] 2018-03-03 08:34
... and when I create the same filter manually, and with a different name, that one gets dropped as well after a while.

**Comment by y2kbugger** [comment] 2018-03-03 13:02
I'm getting filters randomly dropped as well as weird old ones appearing and some getting duplicated randomly. I have just switched phones. I tried to import and there were a bunch of duplicates so I deleted all manually and reimported.

**Comment by y2kbugger** [comment] 2018-03-03 13:21
Also something is going wing with the filters not working correctly. Tasks are not being shown on some filters. Then even when clicking "clear filters" no tasks are shown (this is intermittent though).

I am also utilizing widgets and filter launch icons

**Comment by aubreyz** [comment] 2018-03-03 16:45
Same problem here with defined filters from the tray getting randomly removed -- had to restore from backup several times. 

Also confirm issue with search not working since last update - to be more specific -- when not tray filter set is defined, typing a search filters the items properly. When  any tray filter is active (even one that includes everything) searches do not filter at all.

**Comment by smichel17** [comment] 2018-03-03 19:20
Let's try to keep these issues focused to one bug at a time. This one is about disappearing filters. Please open a new issue for others (if there isn't already one).

**Comment by aubreyz** [comment] 2018-03-04 11:13
Just to update this in case in helps with debugging: 

I again restored the saved filter sets from backup, which worked fine. A day later, about 3 filter sets were missing again completely (I believe the same sets that were elimininated before), and all other filters were duplicated often many times. No other activities had been carried out in the interim apart from viewing of tasks. I am not using widgets. 

Now restoring saved filters again does not resolve the issue either (going back to filters from 3 weeks ago) although all the filters are in the .txt file as expected. At the moment I have hundreds of replicated filters (on average 5 to 10 of each), with many missing.  Not sure how to delete them either except one by one.

**Comment by mpcjanssen** [comment] 2018-03-04 11:52
@aubreyz Re-importing filters will just add the filters now (not replace the filters with the same name). This is caused by the fact that every filter now has a unique id which is created when importing.
I will see if I can add an option to remove all filter and start with a clean slate.

**Comment by aubreyz** [comment] 2018-03-04 12:13
OK that explains some (but not all) of the duplication - but the original duplication was spontaneous (i.e. no import of anything old was done, at least not manually). It also doesn't explain the disappearing filters. 

Just a thought - @y2bbugger mentioned old previously deleted filters somehow restoring (I am not seeing this, possible because I may never have deleted any filters) -- is it possible that an existing saved filters.txt file is somewhere being imported without user intervention? This might explain the spontaneous replication and the reappearance of historical filters (but not the disappearances UNLESS a problem of this sort also overlapped your previous mechanism which did not involve the unique-id on import, and if your old import system was simply an overwrite of the whole).

Anyway - as always thanks for all your work

**Comment by smichel17** [comment] 2018-03-04 12:16
>  import does not import the filters as they were

Can you manually open your `saved_filters.txt` and verify that it contains the filters you are trying to import (ie, make sure the *import* failed, not the export)?

**Comment by aubreyz** [comment] 2018-03-04 12:39
No, I think the import IS importing what is in the file (I am importing from an export made at least 2 weeks ago probably). The filters that are in the file ARE importing, and at least immediately after the import on this occasion all filters that are missing re-appear, and all that are not missing get an extra replicate. 

The problem is that it does not stay that way. As suggested by @nthorne the problem happens afterwards with a delay, and is nothing to do with the import immediately. I have tried to record what I am doing that might trigger a filter-list change, but really I am not doing anything out of the ordinary.  It is just a case of noticing the next day that some filters are gone.  I am scared of doing more imports to restore the lost filters, as I will end up with a massive amount of work to get rid of the replicates until you make the clean slate option. 

A couple of the filters that previously disappeared had quite long names and included (brackets) - perhaps relevant.

**Comment by paullemmens** [comment] 2018-03-04 13:14
Haven't been able to fully read the entire thread. Just wanted to confirm that I also still experience disappearing filters. Haven't yet found a clear trigger, but will keep trying various steps to see if I can manage to write a reprex.

**Comment by paullemmens** [comment] 2018-03-04 13:45
Ok, having read the interaction, in my case I only have disappearing filters. That is, when I (re) import I obviously get duplications, but during interactions with the app no filters are "created". 

Disappearances typically happen, when I forward a task to (say) tomorrow from a filter that only lists today. 

I haven't found consistency which filter gets deleted when I do the above, but one filter is removed from the list.

**Comment by paullemmens** [comment] 2018-03-04 13:47
Ok, having read the interaction, in my case I only have disappearing filters. That is, when I (re) import I obviously get duplications, but during interactions with the app no filters are "created". 

Disappearances typically happen, when I forward a task to (say) tomorrow from a filter that only lists today. 

I haven't found consistency which filter gets deleted when I do the above, but one filter is removed from the list.

Sometimes it actually disappears, but I now also DO see created filters with the name of the context that I'm working in.

**Comment by mpcjanssen** [comment] 2018-03-04 14:02
10.1.5 should already remove the automatically created and updating saved filters.

**Comment by paullemmens** [comment] 2018-03-04 15:19
I've just updated, so need some more time to double check on the (dis)appearing filters. However, I already noticed that filter views are being change when a task (at least, dunno yet for other properties) is completed:

I have a view for @home, today (lua filter with f.due and an os.difftime()). If I then complete a task, the view is changed to including a select(!) subset of tasks both in the past and in the future. 

When then the phone switches of and I open it again (simpletask still in the foreground), then the original view @home today is back.

**Comment by smichel17** [comment] 2018-03-04 16:03
There is some selection issue when completing tasks that only happens when using lua. That's a separate bug from this issue.

**Comment by mpcjanssen** [comment] 2018-03-04 16:24
@aubreyz I didn't include a removal of all saved filters yet. This is easiest to achieve by uninstalling and reinstalling. This will remove all widgets as well though.
Please let me know if you would like a clear all saved filters option.

**Comment by smichel17** [comment] 2018-03-04 17:00
@aubreyz note, you don't actually have to uninstall and reinstall; you can get the same thing by clearing all app data for ST in your *system* preferences.

@mpcjanssen the only time I've wanted that is when importing created a bunch of duplicates. I think an option to replace current filters on import is a better way to go.

**Comment by aubreyz** [comment] 2018-03-04 17:10
@mpcjanssen Clearing app data or reinstalling will presumably also eliminate any other settings I have (correct ?) so not desirable. 

Apart from my problem, I think it essential anyway to have a way to clear existing filters if the new import mechanism does not overwrite old filters with the same name. 

I think The commonest reason for import (apart from backup) will be to reconcile settings across different devices. Here you would have one "main device" and then import the filters on another device. You definitely wouldn't want to have duplication here, or have to manually delete every filter before importing.

**Comment by mpcjanssen** [comment] 2018-03-04 18:01
@aubreyz I restored the behaviour that filters with the same name will be overwritten on import.

**Comment by aubreyz** [comment] 2018-03-04 18:31
@mpcjanssen on upgrading to .9 all existing filters are renamed to filter_100, filter_101 etc etc

Not an issue for me right now, but if happens more generally to everyone that is going to be an issue as the names are lost. Will report back otherwise on bug fixes once I work on it a little. Import of old filters worked fine, but obviously did not overwrite others as the names had changed.

**Comment by mpcjanssen** [comment] 2018-03-04 18:35
Right. I am looking into this issue.

**Comment by mpcjanssen** [comment] 2018-03-04 19:08
@aubreyz can you check with https://cloud.mpcjanssen.nl/index.php/s/t7nYWB6jLyYn9Lp (assuming you use the dropbox version)

**Comment by mpcjanssen** [comment] 2018-03-04 20:23
Note: the current design uses the saved filter xml filename as a unique identifier. This name is based on the name of the filter (it's the base64 encoded string). This way a filter is uniquely identified by its name and no duplicates should be possible.

**Comment by aubreyz** [comment] 2018-03-04 21:22
Sorry @mpcjanssen - I use cloudless, but I upgraded to V10 on playstore. 

I am afraid this crashes immediately after loading (the first time it showed the usual update log, then crashed). Sorry to give you a troublesome weekend......

**Comment by mpcjanssen** [comment] 2018-03-04 22:43
@aubreyz, right I saw the crash. Caused by the fact that "" is not a valid json string. 
This should really be fixed in 10.1.12 which also fixes some filtering issues.

**Comment by aubreyz** [comment] 2018-03-04 22:44
10.1.11 not crashing. When I get a chance I will re-set the app, re-import filters and see how it goes. Thanks for all hard work.

**Comment by mpcjanssen** [comment] 2018-03-04 22:47
@aubreyz does 10.1.11 show the old filter names again? Or still stuff like filter_4.xml

**Comment by paullemmens** [comment] 2018-03-05 13:29
After updating to .15, I did get the filter_n things in my right-hand
drawer that I had to clear out manually before importing the filter file.
Since then so far so good (crosses fingers). Thnx!

**Comment by aubreyz** [comment] 2018-03-05 13:50
@mpcjanssen on reimporting, the imported filters are correctly named now. The filter_4s etc are still there (but because I have not eliminated them yet). 

However a small comment which may be relevant to any other comments you get  -- if I have a single filter with the same name prior to import, as I understand it now it overwrites that filter. However if I have several duplicates (say 3) with the same name prior to the import (because of the prior bug) then after the new import the number of filters does not rise, but there are still 3 - presumably one of which is overwritten.

**Comment by smichel17** [comment] 2018-03-05 17:56
> However if I have several duplicates (say 3) with the same name prior to the import

In the new system (using names to uniquely identify filters), I'm not sure it will be possible to create multiple filters with the same name; that only persists because they were created before the change; I think if you tried to save one of them, it would overwrite the most recent import of the same same.

**Comment by mpcjanssen** [comment] 2018-03-05 18:03
@smichel17 indeed, the old saved filters can still have colliding names. Right now simpletask ensures all the saved filters are listed by looking at the files on the filesystem so this captures all filters so with old file naming (filter_$i.xml) and new file naming (filter_$base64.xml)

**Comment by paullemmens** [comment] 2018-03-05 19:55
Updated to .13 and so far no more issues with (dis)appearing filters or changing views (of filters) when changing ayask.

**Comment by mpcjanssen** [comment] 2018-03-06 13:09
Seems properly fixed now.

**Closed by mpcjanssen** 2018-03-06 13:09 UTC
Labels: bug

**Comment by mpcjanssen** [comment] 2018-03-06 19:19
@aubreyz did you log the crash in the store?

**Comment by aubreyz** [comment] 2018-03-06 19:42
Everything along these lines working great my end now.

**Comment by nthorne** [comment] 2018-03-06 19:58
Seems to be working fine now. Good job!
