### ISSUE TITLE
[Request] Open different todo files from home shortcut

### ISSUE THREAD

**Issue by qoxxxx** [mpcjanssen/simpletask-android#725] opened 2017-02-27 17:10 UTC
I use 2 todo files, that I can switch to from menu "Open todo file". 
It would be nice if I could use 2 app shortcuts (icons) to open the desired todo file directly.

Thanks.

**Comment by mpcjanssen** [comment] 2017-02-28 17:11
Duplicate of #293

**Closed by mpcjanssen** 2017-02-28 17:11 UTC
