### ISSUE TITLE
Wrong color for due date

### ISSUE THREAD

**Issue by Alphalpha007** [mpcjanssen/simpletask-android#593] opened 2016-09-17 15:54 UTC
If due 1 day ago, color shown as green instead of red. More than one day due seems to be working fine.

**Comment by smichel17** [comment] 2016-09-17 21:04
When you talked about this originally on gitter, I was able to reproduce it; however, I can't do so now.

I took a look at the code and found that the text and the color of the due date get set in two different places; the root cause of the bug is that they get out of sync under certain conditions.

I can make them in sync easily, but need to dig a little deeper to figure out which is the right one and what conditions cause them to get out of sync.

**Comment by smichel17** [comment] 2016-09-18 07:00
@Alphalpha007 I believe I've solved the issue with #595. Here's a debug build you can install to test whether the changed worked: http://smichel.me/simpletask/simpletask-android-cloudless-debug.apk

You'll be able to install it alongside the normal simpletask app; it'll appear as Simpletask-DEBUG and have a different icon.

**Comment by Alphalpha007** [comment] 2016-09-19 05:24
Thanks a lot. It was an annoying bug.
I'll take your word for it and wait for the play store update.

**Comment by smichel17** [comment] 2016-09-19 07:27
Are you a part of the simpletask beta?

**Comment by smichel17** [comment] 2016-10-02 21:03
Next version has landed. @Alphalpha007 can you see if this has been fixed?

**Comment by mpcjanssen** [comment] 2016-10-17 08:38
Should be fixed in current play store release. @Alphalpha007 please reopen if it still occurs.

**Closed by mpcjanssen** 2016-10-17 08:38 UTC
