### ISSUE TITLE
Editing properties of a "next" task makes the cursor jump to top of window (first new task)

### ISSUE THREAD

**Issue by paullemmens** [mpcjanssen/simpletask-android#549] opened 2016-08-31 07:35 UTC
Steps to reproduce:

1) Add new task (e.g., click +)
2) type in task and edit properties like list and due.
3) tap "next"/return to add a new task (I use the swype keyboard with the next button)
4) type in task 
5) add property (e.g., list) and close the respective popup with ok.

Now the cursor returns to the first line of the task add window and (effectively) every new/additional property intended for the "next" task (at step 4) is replacing/adding the respective setting for the first task (at step 2) in the window.

**Comment by paullemmens** [comment] 2016-08-31 07:54
Ah, finally found another issue detailing the same problem: #478

**Comment by mpcjanssen** [comment] 2016-09-04 20:22
Handling the cursor in a Edit box is very hard to get right. Will close this as a duplicate of #478.

**Closed by mpcjanssen** 2016-09-04 20:22 UTC
Labels: duplicate
