### ISSUE TITLE
Tasks not selected from widget on cold start

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#811] opened 2017-10-17 22:27 UTC
Steps to reproduce:

- Open ST
- Press the home button, then swipe ST away from the recent apps
    - Alternatively, press the back button until ST closes
- Tap an item in a widget
- ST opens, but the task you tapped is not selected

In contrast, this works if ST is still running in the background:

- Open ST
- Press the home button (not back)
- Tap an item in a widget
- ST opens, with the task you tapped selected

**Comment by mpcjanssen** [comment] 2018-03-06 11:51
Should be fixed by https://github.com/mpcjanssen/simpletask-android/commit/1852cf6481e35a9a53e6b3218ba28f66f7566d79

**Comment by mpcjanssen** [comment] 2018-03-08 20:55
Can't reproduce anymore with 10.1.13

**Closed** 2018-03-08 20:55 UTC
Labels: bug
