### ISSUE TITLE
Specify the archived tasks file (other than done.txt)

### ISSUE THREAD

**Issue by sanzoghenzo** [mpcjanssen/simpletask-android#146] opened 2014-10-13 18:08 UTC
Hi,
could you please add the option to change the name of the archived tasks?
I'm asking this because I would like to be able to add the completed task to my plain text/markdown journal along with my thoughts and social media updates via IFTTT recipes.
It's just a cosmetic issue because I could use done.txt as my journal file, but it would be a little weird :)

**Comment by mpcjanssen** [comment] 2015-01-03 18:35
All groundwork is already in place for this. I am still thinking about how to do the UI. There can be a generic move tasks option, but I am not sure yet.

**Comment by smichel17** [comment] 2016-08-27 16:11
@sanzoghenzo For clarification, are you interested in choosing a unique file name for archived tasks *from a given todo file* (ie, everything from journal.txt archives to journal-done.txt) or a feature to choose individually which file a given task is archived to?

**Comment by sanzoghenzo** [comment] 2016-08-28 12:13
Well, many things changed from my first post, I don't even use simpletask anymore (but I'm planning to go back to it soon).

My original intent was to use a single file, let's call it journal.txt, where I would aggregate all my social media activities (ie an IFTTT recipe that writes my facebook posts at the end of journal.txt), and where simpletask would place the completed tasks. So, to answer your question, all the todos would be using the same archive file.

But now I abandoned the simple text/markdown journal project in favor of Day One on my Mac and Narrate on Android; And used sifttter-redux to aggregate my social activity with the journal via dropbox, and modified it to process the done.txt file and put the tasks completed on the current day in the journal entry.

**Comment by smichel17** [comment] 2016-08-30 16:51
Duplicate of #197

**Comment by mpcjanssen** [comment] 2018-03-06 11:49
Closed for more general #197.

**Closed by mpcjanssen** 2018-03-06 11:49 UTC
Labels: enhancement
