### ISSUE TITLE
if a task is on two lists appear on both

### ISSUE THREAD

**Issue by AnderRasoVazquez** [mpcjanssen/simpletask-android#201] opened 2015-02-19 14:36 UTC
With default behavior we can add a task to more than one list but it only appears on the one that is alphabetically first.

**Comment by Dominik-K** [comment] 2015-04-17 14:30
Are you sure? I can't reproduce what you've said. My tasks appear on each list where I've put them. Tested with version 5.3.0

Which version do you use? Can you give us a simple example, please?

**Comment by mpcjanssen** [comment] 2015-04-17 14:31
I think he means if you group by list, the task will only be show under the first header.

**Comment by mpcjanssen** [comment] 2015-04-17 14:33
Possible duplicate of #153

**Comment by mpcjanssen** [comment] 2015-04-17 14:34
Will close, please reopen if not duplicate of #153

**Closed by mpcjanssen** 2015-04-17 14:34 UTC
