### ISSUE TITLE
Set DUE date to FALSE

### ISSUE THREAD

**Issue by ukrexpo** [mpcjanssen/simpletask-android#368] opened 2016-02-16 16:16 UTC
The best task manager I have ever used. The only remark when I set DUE date for a task I can`t select FALSE in dropdown menu to remove the DUE date. Thus, I have to delete DUE date by hand in the textarea.

**Comment by mpcjanssen** [comment] 2016-02-16 19:26
Duplicate of #367

**Comment by mpcjanssen** [comment] 2016-02-16 19:27
Will be fixed in next version

**Closed by mpcjanssen** 2016-02-16 19:26 UTC
