### ISSUE TITLE
Discarding changes when closing simpletask

### ISSUE THREAD

**Issue by taisnif** [mpcjanssen/simpletask-android#726] opened 2017-03-01 07:23 UTC
When editing an existing task, the changes are no longer present after closing simpletask and starting it again. I noticed this behavior after updating to ST 9.0.0 via fdroid on the Fairphone 2.

**Comment by mpcjanssen** [comment] 2017-03-01 09:27
What do you mean by closing simpletask? Leaving the edit screen using back? Can you describe the exact sequence of actions please?

**Comment by taisnif** [comment] 2017-03-01 10:11
1. Select a task
2. press edit
3. modify task (add some text or a tag, ...)
4. save task
at this point, the changes are still there
5. close the simpletask app (swipe away from the active tasks view in android)
6. open the simpletask app again
at this point, the changes are gone, leaving the task at its original state
I switched back to Simpletask v 8.3.1 and repeated the sequence - everything fine

**Comment by ddisanti** [comment] 2017-03-01 10:47
I can randomly reproduce in Cloudless 9.0.0.
It happens when killing ST right away after saving edits.
But the changes persist if you let a few moments pass before killing ST.

**Comment by mpcjanssen** [comment] 2017-03-01 11:29
Dont close apps by swiping them away. Stuff breaks. All todolist modifications are added to a queue, so they are not written directly. I can look into reducing the delay. But really dont kill apps, its not how android is supposed to work.

**Comment by ddisanti** [comment] 2017-03-01 11:31
Usually, I don't kill apps. I did it just to reproduce this bug.

**Comment by taisnif** [comment] 2017-03-01 11:42
So I have to change my bad behavior ;-) I thout it is common practice to close apps this way, like using the x on the pc. I use Simple Task really a lot, but this kind of thing happened first with 9.0.0. Thats why I opened this issue.

**Comment by mpcjanssen** [comment] 2017-03-01 11:50
Swiping to close is more like pressing ctrl-alt-del on windows and killing the application from the task manager. The equivalent of closing an application is pressing the homw button.
The reason this is an issue now is that the database backend has been removed. So I will look into fixing this anyway. It would be helpful if you can post a log of when it happens.

**Comment by mpcjanssen** [comment] 2017-03-01 11:52
Funny thing. The task is actually saved (it seems) but the cache is not updated. So if you reopen the todo file, the change is there.

**Comment by mpcjanssen** [comment] 2017-03-01 11:56
Also it is very reproducable with updating tasks. In will look into it.

**Comment by taisnif** [comment] 2017-03-01 12:02
Strange thing - but I'm not really a developer ;-) I just removed todo.txt and done.txt from the directory with the file manager. But the entries in Cloudless are still there. Even if I do the bad swipe away.
Btw: The tasklist of android is as easy acdessible as the back-button. So from the users point of view I think its a pretty usual thing to swipe away an app (In my case I just dont want to have 20+ apps in the list).

**Comment by mpcjanssen** [comment] 2017-03-01 12:04
Found the issue I think. The cache is not updated when saving the todolist fro the addtask screen. Cant fix it now but will do it.

**Comment by mpcjanssen** [comment] 2017-03-01 12:08
@taisnif the strange issue is caused by the same stale cache

**Comment by mpcjanssen** [comment] 2017-03-01 12:13
Note that the issue only occurs for updated tasks. Adding or removing tasks does trigger a cache update.

**Comment by taisnif** [comment] 2017-03-01 12:21
I noticed that ,attached you find the log after i did the following steps:
1. deleted all tasks
2. added a Task: "some task A"
3. added another Task: "some task B"
4. modified Task B: "some task B (modified)"
5. share log

[simpletask.txt](https://github.com/mpcjanssen/simpletask-android/files/810656/simpletask.txt)

Finally i want to say thank you for this great app,
for me its the most usable todo app available!

**Comment by mpcjanssen** [comment] 2017-03-01 12:24
Will fix this issue (and the issue when you remove the files) in the next release.

**Closed** 2017-03-01 16:15 UTC
Labels: bug, planned
