### ISSUE TITLE
todo.txt file overwritten when updating to latest version

### ISSUE THREAD

**Issue by lorenzoexe** [mpcjanssen/simpletask-android#253] opened 2015-06-21 11:45 UTC
As in the title, my todo.txt has been (dramatically, since the last backup was quite old) overwritten when I have updated the application to the latest version. I think this is a very serious issue

**Comment by mpcjanssen** [comment] 2015-06-21 11:47
yes this is indeed a very serious issue. You are referring to version 5.4.7? Also I assume you are using the cloudless version?

**Comment by lorenzoexe** [comment] 2015-06-21 11:49
Yes to 5.4.7, and yes, I'm using the cloudless version

**Comment by mpcjanssen** [comment] 2015-06-21 11:50
Also can you send me application log (from setting-> Share log) by email to mpc.janssen@gmail.com if you prefer.

**Comment by lorenzoexe** [comment] 2015-06-21 11:53
Here it is
--------- beginning of /dev/log/main
[ 06-21 13:50:42.390  6264: 6264 D/ActivityThread ]
handleBindApplication:nl.mpcjanssen.simpletask

[ 06-21 13:50:42.390  6264: 6264 D/ActivityThread ]
setTargetHeapUtilization:0.25

[ 06-21 13:50:42.390  6264: 6264 D/ActivityThread ]
setTargetHeapMinFree:524288

[ 06-21 13:50:43.530  6264: 6264 V/Simpletask ]
onCreate

[ 06-21 13:50:43.550  6264: 6264 I/dalvikvm ]
DexOpt: illegal method access (call Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V from Landroid/content/res/XResources$XTypedArray;)

[ 06-21 13:50:43.550  6264: 6264 I/dalvikvm ]
Could not find method android.content.res.TypedArray.<init>, referenced from method android.content.res.XResources$XTypedArray.<init>

[ 06-21 13:50:43.550  6264: 6264 W/dalvikvm ]
VFY: unable to resolve direct method 82: Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V

[ 06-21 13:50:43.550  6264: 6264 D/dalvikvm ]
VFY: replacing opcode 0x70 at 0x0002

[ 06-21 13:50:43.780  6264: 6264 V/Simpletask ]
handleIntent: from m_prefs state

[ 06-21 13:50:43.790  6264: 6264 V/Simpletask ]
setFilteredTasks called: nl.mpcjanssen.simpletask.task.TaskCache@41d15a28

[ 06-21 13:50:43.980  6264: 6264 I/Adreno200-EGL ]
<qeglDrvAPI_eglInitialize:265>: EGL 1.4 QUALCOMM build:  (CL3544079)
Build Date: 03/28/13 Thu
Local Branch: adreno_20130328
Remote Branch: 
Local Patches: 
Reconstruct Branch: 

[ 06-21 13:50:44.050  6264: 6264 D/OpenGLRenderer ]
Enabling debug mode 0

[ 06-21 13:50:44.610  6264: 6293 V/CalendarSync ]
Syncing due/threshold calendar reminders...

[ 06-21 13:50:44.650  6264: 6264 I/Timeline ]
Timeline: Activity_idle id: android.os.BinderProxy@41ce93e0 time:5583679

[ 06-21 13:50:45.060  6264: 6264 V/FileStore ]
Observer adding on: /storage/sdcard1/data/nl.mpcjanssen.simpletask

[ 06-21 13:50:45.070  6264: 6264 V/Simpletask ]
Updating UI because of broadcast

[ 06-21 13:50:45.070  6264: 6264 V/Simpletask ]
handleIntent: from m_prefs state

[ 06-21 13:50:45.070  6264: 6264 V/Simpletask ]
setFilteredTasks called: nl.mpcjanssen.simpletask.task.TaskCache@41d15a28

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{42017140 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{42020590 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{420253f8 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{4202a278 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{4202fea0 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{42034d80 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{42039c48 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:45.420  6264: 6264 W/View     ]
requestLayout() improperly called by android.widget.CheckBox{4203eb28 V.ED..C. ......ID 0,0-32,32 #7f080019 app:id/checkBox} during layout: running second layout pass

[ 06-21 13:50:46.100  6264: 6293 V/CalendarSync ]
Syncing due/threshold calendar reminders...

[ 06-21 13:50:47.460  6264: 6264 V/Simpletask ]
onMenuItemSelected: 2131230803

[ 06-21 13:50:47.460  6264: 6264 I/Timeline ]
Timeline: Activity_launch_request id:nl.mpcjanssen.simpletask time:5586485

[ 06-21 13:50:48.510  6264: 6264 I/Timeline ]
Timeline: Activity_idle id: android.os.BinderProxy@42092698 time:5587535

[ 06-21 13:51:05.060  6264: 6264 W/XPrivacy/XRuntime ]
Get client 10023/exec(logcat -d -v long;null) shell=!restricted 3373 ms

[ 06-21 13:51:05.060  6264: 6264 W/XPrivacy/XRuntime ]
exec 3375 ms

**Comment by mpcjanssen** [comment] 2015-06-21 11:56
Hmm that doesn't help. Do you know how to get the full logcat from your device? (You'll need to be rooted)

**Comment by mpcjanssen** [comment] 2015-06-21 12:03
Also I see you are using sdcard1 is this an extra sdcard which is removable and did you happen to remove it recently?

**Comment by mpcjanssen** [comment] 2015-06-21 12:08
Or another option; did you mount the sdcard1 as USB storage (CM still allows this)

**Comment by lorenzoexe** [comment] 2015-06-21 13:33
No to both questions. Before the overwriting problem happened the todo.txt file was on sdcard0.
Regarding the logcat I could not find a way to get the info at the time the problem happened.

Il 21 giugno 2015 14:08:42 CEST, Mark Janssen <notifications@github.com> ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-21 13:35
For some reason Simpletask thinks the file is on sdcard 1 can you check if sdcard 0 still has a data directory where the file might be?

**Comment by lorenzoexe** [comment] 2015-06-21 13:38
Yes, the sdcard0 has that directory. But as I said before I have intentionally changed the todo.txt directory AFTER the problem happened.

Il 21 giugno 2015 15:35:19 CEST, Mark Janssen <notifications@github.com> ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-21 13:42
Sorry I missed that piece of information. Can you uninstall the app and see if you the problem still occurs? Nb. This will remove your widgets and saved filters and reset your config.

**Comment by lorenzoexe** [comment] 2015-06-21 14:11
Done that, everything fine, no overwriting happened. Still, I would strongly suggests to let the application backup the existing todo.txt file before doing anything else (or renaming it like todo2.txt) so that if something goes wrong nothing gets lost

**Comment by mpcjanssen** [comment] 2015-06-21 14:24
Thatc is definitely a good idea. However I think that the main thing is to figure out why Simpletask thought the fire was empty. 
The problem with backups like that is that it can be easy to accidentally overwrite the backup file as well if no problem is detected.

One more question. Do you use done external synching application?

**Comment by lorenzoexe** [comment] 2015-06-21 15:03
Yes, I use external sync programs but they do not include the folder where simpletask saves todo.txt.

As for the backup files, they should never be deleted: if something like todo2.txt is found (i.e., it already exists) then todo3.txt should be created and so on

Il 21 giugno 2015 16:24:05 CEST, Mark Janssen <notifications@github.com> ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-21 19:57
How would that work in practice? Without manual removing, any change will create a new backup file so you would be at todo100.txt in no time.

I am thinking of having a database in the app which will keep a record of the last 100 versions or something like that, so you can revert to earlier versions easily. The revert would be by sharing to another application to prevent any file system activity.

**Comment by lorenzoexe** [comment] 2015-06-21 21:02
Yes, you're right, but I thought that such an operation could be done only when the application gets updated (since the problem seems to lie there), so that the number of todo.txt files would be small.

Another way would be to ask confirmation to the user if the todo file is the right one after the update, if it isn't the application would load the old one (temporarily copied with another name the first time the application is started after the update).

However, I agree that the database is the best idea on the long run; I only wonder if it is significantly more complicated than trying to work on some improved version of the logic to backup the todo file.
Anyway, I think it would be still convenient to implement a function in order to be able to manually backup the todo.txt from inside the application.

Il 21 giugno 2015 21:57:54 CEST, Mark Janssen <notifications@github.com> ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-21 21:29
Let me answer your response in parts. First and most importantly, backing up your todo.txt is very easy. In the app just clear all filters and selections and select the share icon, you can then put a plain text copy of your list in whatever app accepts plain text.
I usually send myself an email.

A database for older versions is not too complex. Also for the record, after an update the settings are kept and Simpletask should not change the todo file at all.

Detecting updates is not easily done if it's possible at all  and I can't imagine a scenario where an update should corrupt the todo.txt file. What I can imagine is that the restart of Simpletask caused by the update actually had more to do with it.

So a couple of additional questions:

1) when was the last time you saw the actual todo file with correct contents on the sdcard (not in simpletask)
2) what was the exact location of the todo.txt at that point?
3) What happened exactly (as far as you can remember) after the update, was simpletask showing an empty screen? Were there any popup messages etc.
4) what actions did you take afterwards?

**Comment by vojtechkral** [comment] 2015-06-22 10:14
Another way would be versioning `todo.txt` in git, hg or similar. However that wouldn't probably be easy to implement...

**Comment by lorenzoexe** [comment] 2015-06-22 13:01
Sorry, I didn't tought it was so simple to save the todo file from 
inside the application!

1) I have never opened the todo file outside simpletask before this 
problem happened

2) When the problem happened the todo file was in 
/storage/emulated/0/data/nl.mpcjanssen.simpletask

3) The events, as far as I remember, have been these ones:
   a) I've updated simpletask (I haven't opened it) using f-droid;
   b) I've added a task to simpletask sharing a link from the 
application muzei. A message appeared saying that the operation was 
successfull (I still haven't opened simpletask);
   c) About two days later I have opened simpletask to add some tasks 
and I have found only the last link saved: all other todos where not 
there. I've then browsed to the todo.txt file location and I've found 
that it was 300 B circa.


Il 21/06/2015 23:29, Mark Janssen ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-22 15:06
Thanks for describing the sequence of events. This seems like a manifestation of #251

What probably happened:

* You installed a version between 5.4.0 and 5.4.6 which had bug #251 
* You added a link using "Share to..."
* Simpletask started in the background to and loading the todo file into memory.
* Before this could finish, the Sharing handling in Simpletask wrote the empty taskcache plus the one link to the todo file nuking the contents.

So I suggest to close this issue and I have logged #254 for more intuitive and automatic backup.

**Comment by lorenzoexe** [comment] 2015-06-22 15:37
Yes, automatic backup would be a simple yet great idea!

Il 22/06/2015 17:06, Mark Janssen ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-22 16:18
Closed as duplicate of #251

**Closed by mpcjanssen** 2015-06-22 16:18 UTC

**Comment by mpcjanssen** [comment] 2015-06-23 18:09
@lorenzoexe please keep tracking #254 for updates. The functionality to put older versions in the database is there.
What I still need to add is a way to limit the amount of backups and a UI to get to it.

**Comment by lorenzoexe** [comment] 2015-06-24 09:32
What do you mean "limit the amount of backups"? You could delete those 
with a timestamp older than a given one (which you could ask as an input 
to the user in the settings)


Il 23/06/2015 20:09, Mark Janssen ha scritto:

**Comment by mpcjanssen** [comment] 2015-06-24 09:59
Currently I keep the last 10. The idea is to make this configurable. A day
range would make more sense though.
