### ISSUE TITLE
Cannot connect to Nextcloud

### ISSUE THREAD

**Issue by lamalediction** [mpcjanssen/simpletask-android#977] opened 2019-06-02 07:47 UTC
Hi,
This seems similar to issue #915 but I'm also opening a new ticket because it's been closed.
The server is running Nextcloud 16.
I downloaded SimpleTask Nextcloud V10.3.0 (3211) on Google Play Store.
When I try to connect to my Nextcloud account I get a message that says "login failed: HOST_NOT_AVAILABLE".
As far as I can tell there is no issue with the server, I can access my files through the Nextcloud Sync app, I can access my contacts and calendars through DAVx5 (formerly DavDroid).
I'll post the log in a second post but I seem to be getting the same errors ("Simpletask: handleIntent: not authenticated" and "Lua error: bad argument: table expected, got nil )")
Many thanks in advance and also thank you very much for this great app!

**Comment by lamalediction** [comment] 2019-06-02 07:51
Also I just tried creating an app password for SimpleTask and looking at "Devices and sessions" in Settings > Security on the webpage seems to indicate that it successfully connected.

**Comment by lamalediction** [comment] 2019-06-02 07:57
Here's the log, I changed the domain name to ncloud.domain.com .

--------- beginning of main
06-02 09:04:22.722  1972  1972 E etask.nextclou: Not starting debugger since process cannot load the jdwp agent.
06-02 09:04:22.811  1972  1972 I Perf    : Connecting to perf service.
06-02 09:04:22.840  1972  1972 I MultiDex: VM with version 2.1.0 has multidex support
06-02 09:04:22.840  1972  1972 I MultiDex: Installing application
06-02 09:04:22.840  1972  1972 I MultiDex: VM has multidex support, MultiDex support library is disabled.
06-02 09:04:22.855  1972  1972 D QueryStore: Saved applyFilter ids: []
06-02 09:04:22.856  1972  1972 I TodoApplication: onCreate()
06-02 09:04:22.857  1972  1972 I TodoApplication: Created todolist nl.mpcjanssen.simpletask.task.TodoList@bae19b2
06-02 09:04:22.857  1972  1972 I TodoApplication: Started Simpletask nextcloud v10.3.0 (3211)
06-02 09:04:22.860  1972  1972 I TodoApplication: Scheduling daily UI updateCache alarm, first at Mon Jun 03 00:02:00 GMT+02:00 2019
06-02 09:04:22.861  1972  1972 I TodoApplication: Scheduling task list reload
06-02 09:04:22.948  1972  1972 I Simpletask: onCreate
06-02 09:04:23.020  1972  1972 I Simpletask: onResume
06-02 09:04:23.020  1972  1972 D TodoList: Reload: Main activity resume
06-02 09:04:23.020  1972  1972 I Util    : Sending file sync start broadcast
06-02 09:04:23.021  1972  1972 I Util    : Sending file sync done changed broadcast
06-02 09:04:23.021  1972  1972 I Simpletask: handleIntent: not authenticated
--------- beginning of system
06-02 09:04:23.022  1972  1972 I Timeline: Timeline: Activity_launch_request time:12268203 intent:Intent { cmp=nl.mpcjanssen.simpletask.nextcloud/nl.mpcjanssen.simpletask.remote.LoginScreen }
06-02 09:04:23.042  1972  1972 D Event   : update UI for event RESUME
06-02 09:04:23.045  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:04:23.045  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:04:23.045  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:04:23.046  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:04:23.046  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:04:23.047  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:04:23.063  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@21e7108
06-02 09:04:23.145  1972  2030 I Adreno  : QUALCOMM build                   : cf57c9c, I1cb5c4d1cc
06-02 09:04:23.145  1972  2030 I Adreno  : Build Date                       : 09/23/18
06-02 09:04:23.145  1972  2030 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.01
06-02 09:04:23.145  1972  2030 I Adreno  : Local Branch                     : 
06-02 09:04:23.145  1972  2030 I Adreno  : Remote Branch                    : 
06-02 09:04:23.145  1972  2030 I Adreno  : Remote Branch                    : 
06-02 09:04:23.145  1972  2030 I Adreno  : Reconstruct Branch               : 
06-02 09:04:23.145  1972  2030 I Adreno  : Build Config                     : S L 6.0.7 AArch64
06-02 09:04:23.151  1972  2030 I Adreno  : PFP: 0x005ff112, ME: 0x005ff066
06-02 09:04:23.158  1972  2030 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
06-02 09:04:23.158  1972  2030 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
06-02 09:04:23.159  1972  2030 I OpenGLRenderer: Initialized EGL, version 1.4
06-02 09:04:23.159  1972  2030 D OpenGLRenderer: Swap behavior 2
06-02 09:04:29.201  1972  1972 I AssistStructure: Flattened final assist data: 4316 bytes, containing 1 windows, 13 views
06-02 09:04:30.824  1972  2004 I etask.nextclou: ProcessProfilingInfo new_methods=1815 is saved saved_to_disk=1 resolve_classes_delay=8000
06-02 09:05:03.222  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
06-02 09:05:06.443  1972  1972 I AssistStructure: Flattened final assist data: 4412 bytes, containing 1 windows, 13 views
06-02 09:05:11.531  1972  1972 I AssistStructure: Flattened final assist data: 4428 bytes, containing 1 windows, 13 views
06-02 09:06:07.710  1972  1972 I FSQ     : -> login
06-02 09:06:07.713  1972  2124 I FSQ     : <- login
06-02 09:06:07.719  1972  2124 D NetworkUtils: Searching known-servers store at /data/user/0/nl.mpcjanssen.simpletask.nextcloud/files/knownServers.bks
06-02 09:06:07.720  1972  2124 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-02 09:06:07.775  1972  2124 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
06-02 09:06:07.775  1972  2124 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
06-02 09:06:07.775  1972  2124 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
06-02 09:06:07.785  1972  2124 D OwnCloudClient #0: Creating OwnCloudClient
06-02 09:06:07.908  1972  2124 D OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/
06-02 09:06:07.915  1972  2124 D AdvancedSslSocketFactory: Creating SSL Socket with remote ncloud.domain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@e84674d
06-02 09:06:07.915  1972  2124 D AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
06-02 09:06:07.926  1972  2124 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.Java8FileDescriptorSocket
06-02 09:06:07.928  1972  2124 I ServerNameIndicator: SNI done, hostname: ncloud.domain.com
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: Synchronized /: Unexpected exception
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:308)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:144)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:84)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:24)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:16)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:9)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 09:06:08.565  1972  2124 E ReadFolderRemoteOperation: 	at java.lang.Thread.run(Thread.java:764)
06-02 09:06:08.565  1972  2124 D LoginScreen: Unexpected exception
06-02 09:06:08.565  1972  2124 D LoginScreen: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-02 09:06:08.565  1972  2124 D LoginScreen: -1
06-02 09:06:08.566  1972  2124 D LoginScreen: Login failed: HOST_NOT_AVAILABLE
06-02 09:06:08.583  1972  1972 I Toast   : Show toast from OpPackageName:nl.mpcjanssen.simpletask.nextcloud, PackageName:nl.mpcjanssen.simpletask.nextcloud
06-02 09:07:46.679  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f1020c2
06-02 09:07:46.720  1972  1972 I Simpletask: onCreate
06-02 09:07:46.762  1972  1972 I Simpletask: onResume
06-02 09:07:46.762  1972  1972 D TodoList: Reload: Main activity resume
06-02 09:07:46.762  1972  1972 I Util    : Sending file sync start broadcast
06-02 09:07:46.763  1972  1972 I Util    : Sending file sync done changed broadcast
06-02 09:07:46.763  1972  1972 I Simpletask: handleIntent: not authenticated
06-02 09:07:46.763  1972  1972 I Timeline: Timeline: Activity_launch_request time:12424415 intent:Intent { cmp=nl.mpcjanssen.simpletask.nextcloud/nl.mpcjanssen.simpletask.remote.LoginScreen }
06-02 09:07:46.780  1972  1972 D Event   : update UI for event RESUME
06-02 09:07:46.781  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:46.781  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:07:46.781  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:46.782  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:46.782  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:07:46.782  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:46.798  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@37bba03
06-02 09:07:48.497  1972  1972 I Timeline: Timeline: Activity_launch_request time:12426149 intent:Intent { cmp=nl.mpcjanssen.simpletask.nextcloud/nl.mpcjanssen.simpletask.DebugInfoScreen }
06-02 09:07:48.534  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@373be1b
06-02 09:07:57.049  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a4c4bb5
06-02 09:07:57.070  1972  1972 I Simpletask: onCreate
06-02 09:07:57.099  1972  1972 I Simpletask: onResume
06-02 09:07:57.099  1972  1972 D TodoList: Reload: Main activity resume
06-02 09:07:57.099  1972  1972 I Util    : Sending file sync start broadcast
06-02 09:07:57.099  1972  1972 I Util    : Sending file sync done changed broadcast
06-02 09:07:57.099  1972  1972 I Simpletask: handleIntent: not authenticated
06-02 09:07:57.099  1972  1972 I Timeline: Timeline: Activity_launch_request time:12434752 intent:Intent { cmp=nl.mpcjanssen.simpletask.nextcloud/nl.mpcjanssen.simpletask.remote.LoginScreen }
06-02 09:07:57.142  1972  1972 D Event   : update UI for event RESUME
06-02 09:07:57.143  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:57.143  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:07:57.143  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:57.144  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:57.144  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:07:57.144  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:57.163  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9e3063a
06-02 09:07:59.724  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@2f87f81
06-02 09:07:59.743  1972  1972 I Simpletask: onCreate
06-02 09:07:59.763  1972  1972 I Simpletask: onResume
06-02 09:07:59.763  1972  1972 D TodoList: Reload: Main activity resume
06-02 09:07:59.763  1972  1972 I Util    : Sending file sync start broadcast
06-02 09:07:59.765  1972  1972 I Util    : Sending file sync done changed broadcast
06-02 09:07:59.765  1972  1972 I Simpletask: handleIntent: not authenticated
06-02 09:07:59.766  1972  1972 I Timeline: Timeline: Activity_launch_request time:12437418 intent:Intent { cmp=nl.mpcjanssen.simpletask.nextcloud/nl.mpcjanssen.simpletask.remote.LoginScreen }
06-02 09:07:59.793  1972  1972 D Event   : update UI for event RESUME
06-02 09:07:59.794  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:59.794  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:07:59.794  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:59.797  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:59.797  1972  1972 D Simpletask: Update applyFilter bar
06-02 09:07:59.797  1972  1972 E Util    : Lua error: bad argument: table expected, got nil )
06-02 09:07:59.824  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@49918df
06-02 09:08:00.526  1972  1972 I AssistStructure: Flattened final assist data: 4316 bytes, containing 1 windows, 13 views
06-02 09:08:25.712  1972  1972 I AssistStructure: Flattened final assist data: 4412 bytes, containing 1 windows, 13 views
06-02 09:08:31.618  1972  1972 I AssistStructure: Flattened final assist data: 4428 bytes, containing 1 windows, 13 views
06-02 09:08:41.804  1972  1972 I FSQ     : -> login
06-02 09:08:41.806  1972  2124 I FSQ     : <- login
06-02 09:08:41.806  1972  2124 D OwnCloudClient #1: Creating OwnCloudClient
06-02 09:08:41.813  1972  2124 D OwnCloudClient #1: REQUEST PROPFIND /remote.php/webdav/
06-02 09:08:41.818  1972  2124 D AdvancedSslSocketFactory: Creating SSL Socket with remote ncloud.domain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@e84674d
06-02 09:08:41.818  1972  2124 D AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
06-02 09:08:41.825  1972  2124 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.Java8FileDescriptorSocket
06-02 09:08:41.825  1972  2124 I ServerNameIndicator: SNI done, hostname: ncloud.domain.com
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: Synchronized /: Unexpected exception
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:308)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:144)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:84)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:24)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:16)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:9)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 09:08:42.252  1972  2124 E ReadFolderRemoteOperation: 	at java.lang.Thread.run(Thread.java:764)
06-02 09:08:42.253  1972  2124 D LoginScreen: Unexpected exception
06-02 09:08:42.253  1972  2124 D LoginScreen: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-02 09:08:42.253  1972  2124 D LoginScreen: -1
06-02 09:08:42.253  1972  2124 D LoginScreen: Login failed: HOST_NOT_AVAILABLE
06-02 09:08:42.281  1972  1972 I Toast   : Show toast from OpPackageName:nl.mpcjanssen.simpletask.nextcloud, PackageName:nl.mpcjanssen.simpletask.nextcloud
06-02 09:08:44.015  1972  1972 I Timeline: Timeline: Activity_launch_request time:12481667 intent:Intent { cmp=nl.mpcjanssen.simpletask.nextcloud/nl.mpcjanssen.simpletask.DebugInfoScreen }
06-02 09:08:44.058  1972  1972 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8ef3237
06-02 09:09:07.103  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
06-02 09:09:08.762  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
06-02 09:09:18.707  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
06-02 09:09:20.349  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
06-02 09:09:27.026  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
06-02 09:09:33.236  1972  1972 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!

**Comment by mpcjanssen** [comment] 2019-06-02 13:05
Duplicate of #974

**Closed** 2019-06-02 13:05 UTC

**Comment by lamalediction** [comment] 2019-06-02 14:05
Sorry didn't see the other one. Thanks very much for looking into it!

**Comment by mpcjanssen** [comment] 2019-06-03 08:22
@lamalediction no problem, please check the other issue for further updates.
