### ISSUE TITLE
Compatibility with todo.txt OR desktop editing?

### ISSUE THREAD

**Issue by gladomat** [mpcjanssen/simpletask-android#767] opened 2017-07-26 13:10 UTC
I just found this app and found it intriguing. I set up some tasks on my phone then synced it to my owncloud. When I tried to open it with todo.sh cli it didn't recognize it. The files are not really the same (simpletask list.txt vs todo.txt). I was wondering why that is so? How do you edit it on your desktop? I don't want to keep looking at my phone when I need to see what tasks are next or while entering new tasks, especially when I'm working on my computer.

**Comment by smichel17** [comment] 2017-07-26 14:00
It should be todo.txt compatible. What differences are you seeing? Note there is a setting `Keep priority in completed tasks` which should be disabled for compatibility.

**Comment by gladomat** [comment] 2017-07-26 14:48
Ah okay, I see. It works!

What do you use as a desktop app?

**Comment by smichel17** [comment] 2017-07-26 15:50
Honestly, simpletask works so much better than any other todo.txt app or program I've used, due to threshold dates and saved filters. I almost exclusively use my phone for task management now.

In the past I've used a gnome [shell extension](https://extensions.gnome.org/extension/570/todotxt/), or just plain vim. Although, just now when I was getting the link to the extension, I came across [this one](https://extensions.gnome.org/extension/1238/time/) which looks like it's a bit more powerful.

**Comment by mpcjanssen** [comment] 2017-07-26 16:42
I use Simpletask as well but occasionally I use http://todo.martinsgill.co.uk for a quick view in the browser.

**Comment by doranism** [comment] 2017-08-05 20:24
There is a list of (desktop) software for todo.txt on [www.todotxt.com](url). On Windows I used todotxt.net for a while. 
Afaik there is no desktop app for todo.txt that supports MYN. Because of that I only use Simpletask for task management now and I set up my phone as a "second screen" for my desktop. I type new tasks directly from my desktop keyboard to my phone via Android app "WiFiKeyboard". This works very well for me.

**Comment by gladomat** [comment] 2017-08-07 09:04
Thanks for the feedback. Do you all used GTD or MYN or a mix or your own concoction? I tried GTD but I find it too rigid.

**Comment by mpcjanssen** [comment] 2017-08-07 18:15
I use a mix. Project list and reviews from gtd. Actual task management and deferral from myn

**Comment by ravl1084** [comment] 2017-09-20 18:01
Could you provide some details on how you synced it to your desktop? I'm trying to use NextCloud and I can't sync the file Simpletask uses

**Comment by smichel17** [comment] 2018-03-10 09:23
@ravl1084, I:

1. Uploaded my todo.txt file to nextcloud
2. Opened the nextcloud app and marked my todo.txt file as both a favorite and available offline.
3. Pointed ST Cloudless at the file in Nextcloud's directory:
```
~/Android/data/com.nextcloud.client/files/nextcloud/<my-account-name>/path/to/todo.txt
```

This setup is not as reliable for syncing as if you use [Simpletask for Nextcloud](https://play.google.com/store/apps/details?id=nl.mpcjanssen.simpletask.nextcloud), but I don't use other clients enough to care :P

**Comment by Robinlovelace** [comment] 2019-12-07 23:08
Heads-up, I think there are compatibility issues, at least with todo.sh. I see this for issues that I've marked as 'done' in SimpleTask:

```
25 x 2019-11-30 2019-09-17 Update MSc projects
```

The x was added by SimpleTask but does not close it in the CLI tool I think. Any ideas?

**Comment by mpcjanssen** [comment] 2019-12-08 04:27
@Robinlovelace the issue is the preceding `25` . I don't think simpletask did this. By design a completed task will always start witj `x`

**Comment by Robinlovelace** [comment] 2019-12-08 10:22
The 25 is added by `todo.sh`. The line does start with x:

```
cat ~/Dropbox/todo/todo.txt | grep MSc
x 2019-11-30 2019-09-17 Update MSc projects
```

It seems todo.sh does not realise that tasks that start with x should be closed. I'm running 

```
todo.sh -V
TODO.TXT Command Line Interface v@DEV_VERSION@

First release: 5/11/2006
Original conception by: Gina Trapani (http://ginatrapani.org)
Contributors: http://github.com/ginatrapani/todo.txt-cli/network
License: GPL, http://www.gnu.org/copyleft/gpl.html
More information and mailing list at http://todotxt.com
Code repository: http://github.com/ginatrapani/todo.txt-cli/tree/master
```

**Comment by Robinlovelace** [comment] 2019-12-08 10:27
To clarify with a larger example, here's some output from `todo.sh` that shows that there are 2 versions of the task, one open (with the x added by SimpleTask) and one closed:

```
todo.sh ls | wc
49     427    2842
$ todo.sh listall|wc
301    2956   20273
$ todo.sh ls MSc    
25 x 2019-11-30 2019-09-17 Update MSc projects
--
  TODO: 1 of 47 tasks shown
$ todo.sh lsa MSc
25 x 2019-11-30 2019-09-17 Update MSc projects
00 x 2019-12-01 2019-09-17 Update MSc projects
--
  TODO: 1 of 47 tasks shown
DONE: 1 of 250 tasks shown
total 2 of 297 tasks shown
```

**Comment by mpcjanssen** [comment] 2019-12-08 16:25
Ah the 25 comes from todo.sh. In that case I have no idea what is causing this. Maybe a mix of line endings?

**Comment by Robinlovelace** [comment] 2019-12-08 23:28
Just realised you need to run

```
todo.sh archive
```

For it to move the done items into `done.txt`.

Reprex:

```
todo.sh archive                                            
x 2019-11-30 2019-09-17 Update MSc projects
x 2019-12-01 2019-12-01 Test from Android
x 2019-12-02 (A) 2019-12-01 Presentation for Tuesday 
...
TODO: /home/robin/Dropbox/todo/todo.txt archived.
```

So problem solved. It works!

**Comment by Robinlovelace** [comment] 2019-12-08 23:28
P.s. this is documented here: https://github.com/todotxt/todo.txt-cli/wiki/Usage

**Comment by mpcjanssen** [comment] 2019-12-09 02:07
Glad it works. Thanks for letting me know.

**Closed by mpcjanssen** 2019-12-09 02:07 UTC
Labels: question
