### ISSUE TITLE
Ticking check box results in multiplication of all tasks in list

### ISSUE THREAD

**Issue by abattech** [mpcjanssen/simpletask-android#252] opened 2015-06-20 03:45 UTC
When i check a task as done, all other tasks multiply. I see 3-6 copies of every task in my list. Todo.txt on disk seems fine.

**Comment by mpcjanssen** [comment] 2015-06-20 03:48
It works fine for me. Which version are you using and are you on the dropbox version?

**Comment by abattech** [comment] 2015-06-20 03:49
Simpletask cloudless v5.4.5 (1557)

**Comment by mpcjanssen** [comment] 2015-06-20 03:51
Does this also happen with a small test todo.txt? If not could you mail me a copy of your todo.txt or any file that has the same behavior?

**Comment by abattech** [comment] 2015-06-20 17:53
Sent you email

**Comment by jfoster3** [comment] 2015-06-24 12:37
I've been getting the same behavior on Simpletask cloudless v5.4.7 (1559).

**Comment by mpcjanssen** [comment] 2015-06-24 12:45
@jfoster3 @abattech 

I can't reproduce this at all. 

Couple of questions:

1) Does the same behavior occur if disable check boxes in settings and complete tasks via the menu?
2) What theme are you using, Material or Holo
3) Can you provide a full logcat of when the problem occurs (possibly by email)

**Comment by jfoster3** [comment] 2015-06-24 14:09
Disabling the completion checkboxes does seem to do away with the issue. I
have not been able to replicate the issue without the checkboxes.

As for theme, I've used both Holo and Material and had the same behavior.

On the log... I'm not well versed in retrieving android logs. Do I need to
have something like aLogcat running to capture the logs?

**Comment by mpcjanssen** [comment] 2015-06-24 15:31
Could you try with the test builds at http://mpcjanssen.nl/files/simpletask/latest ?

It might be wise to make a backup of todo.txt because this is a WIP release.

**Comment by abattech** [comment] 2015-06-24 16:11
No improvement for me.

**Comment by jfoster3** [comment] 2015-06-25 13:21
No improvement. That actually made the duplication happen with the
completion checkboxes disabled.

**Comment by mpcjanssen** [comment] 2015-06-25 13:27
At least it's consistent now. :) I have a hunch of what might be causing
this. If you route the phone when this happens, do the duplicates disappear?

**Comment by jfoster3** [comment] 2015-06-25 13:33
Did you mean rotate? If so, no. The duplicates remain.

**Comment by mpcjanssen** [comment] 2015-06-25 13:41
I will create another test build which should give more visual. Feedback. What sort are you using?

**Comment by mpcjanssen** [comment] 2015-06-25 13:56
Also are the duplicated tasks also saved to the todo.txt file?

**Comment by jfoster3** [comment] 2015-06-25 14:01
Galaxy S4

And no, it does not appear to save the dupes to the file now.

**Comment by mpcjanssen** [comment] 2015-06-25 14:02
I mean what is the sort you configured for the tasks (in the filter)

**Comment by jfoster3** [comment] 2015-06-25 14:05
Didn't have filters or sorts defined.

**Comment by mpcjanssen** [comment] 2015-06-25 18:46
@jfoster3 could you try again with the latest build at the previous URL? Please note this is a super alpha build so backup your todo.txt and done.txt. I just want to know if the issue has been fixed in this build.

**Comment by jfoster3** [comment] 2015-06-25 19:15
I think you got it. I can no longer trigger the duplication issue with that
alpha build. I tried with the completion checkboxes enabled and disabled.
Seems to be clean in both cases.

**Comment by mpcjanssen** [comment] 2015-06-25 20:46
Hmm I just noticed @jfoster is it the case that clicking the check box doesn't actually update the file now?

**Comment by jfoster3** [comment] 2015-06-25 21:25
Seems to be updating ok, with checkboxes and without. I'm seeing tasks
moving from todo.txt to done.txt.

**Comment by mpcjanssen** [comment] 2015-06-25 21:38
ok great, please uninstall the alpha version, it's a bit broken with regards to background todo file updates. I think I have a more stable version now, but I want to testdrive it myself for a while.

**Comment by jfoster3** [comment] 2015-06-25 22:26
Will do. Thanks for a great app!

**Closed** 2015-06-25 22:57 UTC

**Comment by mpcjanssen** [comment] 2015-06-26 01:02
@jfoster3 the new versions in latest are the ones I will be testdriving for the next week. So if you feel up to it you can also use it. This is still not production ready, however it does store backups of at least the todo.txt in an internal database so recovery is possible.

Do note that recovery requires some hacking at the moment, I am working on a GUI for it.
