### ISSUE TITLE
When creating a new task, app is crashing when selecting List or Tag from menu

### ISSUE THREAD

**Issue by jason-mehmel** [mpcjanssen/simpletask-android#361] opened 2016-02-08 07:19 UTC
The app still functions through typing, I can type new or existing tags and lists with no crashing, but using the menu for either list or tag causes a crash. Samsung Galaxy S5.

**Comment by mpcjanssen** [comment] 2016-02-08 07:42
I think I know the cause. It should only occur if the edit box is empty. If it is occurring for other scenarios for you @jason-mehmel  could you please include a logcat here?

**Comment by jason-mehmel** [comment] 2016-02-08 07:53
Just tested it, and you're right! If the edit box has content, the crash does not occur.

(If I do find it again, how do I get a logcat from my phone? Sorry for the newb question.)

**Comment by pruperting** [comment] 2016-02-08 10:28
Happens to me as well when I try to select a context. Seems to crash even if I have typed in a new context. Doesn't crash if I have typed in something to the main data entry window first. Can't see how to attach a logcat to this thread, though I have one. I can email you if needed.

**Comment by pruperting** [comment] 2016-02-08 10:30
Aha, need to use desktop view...
[logcat_and_device_info.zip](https://github.com/mpcjanssen/simpletask-android/files/121419/logcat_and_device_info.zip)

**Comment by mpcjanssen** [comment] 2016-02-08 10:32
@pruperting logcat confirms the cause of the crash. This will be fixed in next version. 

@jason-mehmel I have added functionality that uncaught exceptions will also be logged in the application log. So you can just share the logging from the settings.

**Comment by mpcjanssen** [comment] 2016-02-08 13:58
Waiting with close until confirmed fixed in 7.0.12

**Comment by jason-mehmel** [comment] 2016-02-09 04:15
Also adding my log... 
[simpletask.txt](https://github.com/mpcjanssen/simpletask-android/files/122577/simpletask.txt)

**Comment by pruperting** [comment] 2016-02-09 08:05
Seems to work fine for me now. Many thanks for super quick response.

**Closed** 2016-02-09 12:45 UTC

**Comment by jason-mehmel** [comment] 2016-02-09 17:20
Just a quick note to say thanks for the response, and thanks for the app!
