### ISSUE TITLE
Changing orientation mode clears text

### ISSUE THREAD

**Issue by qazip** [mpcjanssen/simpletask-android#846] opened 2018-01-01 13:24 UTC
I'm using the latest version from FDroid and whenever I've some text and I change the orientation mode (for example, to landscape), the text is deleted.

**Comment by smichel17** [comment] 2018-01-01 14:08
Duplicate of #843, I think.

**Comment by mpcjanssen** [comment] 2018-01-01 14:10
Closed as duplicate of #843. @qazip if this is a different issue, please reopen this issue and explain how it's different.

**Closed by mpcjanssen** 2018-01-01 14:10 UTC
