### ISSUE TITLE
Edit shared/sent tasks stoped working

### ISSUE THREAD

**Issue by tomtom** [mpcjanssen/simpletask-android#298] opened 2015-09-04 15:39 UTC
Since one of the later versions (IIRC after implementing the material design guideline), the option "edit shared/sent tasks" stopped working -- at least when using the German locale ("Geteilte Aufgaben bearbeiten"). When I press the option, a text box with no further explanation appears. IIRC this was a boolean value / checkbox. When I send a task to simpletask, the task is immediately added to the todo list, which is annoying when the task contains a newline.

**Comment by mpcjanssen** [comment] 2015-09-04 17:39
Duplicate of #292 . Will be fixed in next version.

**Comment by mpcjanssen** [comment] 2015-10-19 09:31
Fixed in latest release

**Closed** 2015-10-19 09:31 UTC
