### ISSUE TITLE
FDroid Appears To Have Wrong App

### ISSUE THREAD

**Issue by farverio** [mpcjanssen/simpletask-android#963] opened 2019-03-10 21:48 UTC
After downloading the simple task nextcloud app on two devices from Fdroid, it seems they are not the correct app. There is no way to connect to next cloud or manage the connection to confirm notes are being synced

**Comment by Gregory-K** [comment] 2019-03-11 00:14
#816

**Comment by smichel17** [comment] 2019-03-11 07:05
Correct, this is a duplicate of #816.

**Closed by smichel17** 2019-03-11 07:05 UTC
